---
- name: Check if user password is expired # noqa 305 - no alternative to shell
  no_log: "{{ no_log_flag }}" # don't log decrypted passwords in responses
  shell:
    cmd: sshpass -p '{{ gateway_default_password }}' ssh {{ ansible_ssh_extra_args }} {{ ansible_user }}@{{ ansible_host }} "chage --list {{ ansible_user }}"
  register: expired
  changed_when: false
  failed_when: "'Connection refused' in expired.stderr"

- name: Update expired ssgconfig user password
  when: expired.rc != 0 and 'Your password has expired' in expired.stderr
  no_log: "{{ no_log_flag }}" # don't log decrypted passwords in responses
  expect:
    command: sshpass -p '{{ gateway_default_password }}' ssh {{ ansible_ssh_extra_args }} {{ ansible_user }}@{{ ansible_host }}
    timeout: "{{ gateway_ssh_timeout }}"
    responses:
      "'s password:": "{{ gateway_default_password }}"
      "UNIX password:": "{{ gateway_default_password }}"
      "New password:": "{{ gateway_ssgconfig_password }}"
      "Retype new password:": "{{ gateway_ssgconfig_password }}"
  register: status
  changed_when: "'passwd: all authentication tokens updated successfully' in status.stdout"