---
all:
  hosts:
  children:
    gateway:
      children:
        gateway_mysql:
          children:
            gateway_primary_db:
              hosts:
                target-gw.placeholder.com:
                  src: source-db-gw.placeholder.com
            gateway_failover_db:
              hosts:
                failover-gw.placeholder.com:
                  src: source-failover-db-gw.placeholder.com
        gateway_processing_node:
          hosts:
            target-processing-gw.placeholder.com:
              src: source-processing-gw.placeholder.com
        gateway_hsm:
          hosts:
        gateway_papim:
          chilren:
            gateway_papim_source:
              hosts:
            gateway_papim_install:
              hosts:
    hsm:
      children:
        hsm_luna7:
          hosts:
            luna7.placeholder.com:
              ansible_user: admin
              ansible_connection: ssh
