---
all:
  hosts:
  children:
    gateway:
      children:
        gateway_mysql:
          children:
            gateway_primary_db:
              hosts:
                post-upgrade-gw:
                  src: pre-upgrade-gw
