---
# New value for Gateway cluster.hostname cluster property. Only updated if set to non-empty string.
new_cluster_hostname: ""

# Values for replacing all old OTK JDBC URLs' hostnames with the new one. URLs are only updated if both are set to non-empty strings.
old_otk_jdbc_hostname: ""
new_otk_jdbc_hostname: ""

# Values for updating all old OTK callback URLs' hostnames with the new one. URLs are only updated if both are set to non-empty strings.
old_callback_hostname: ""
new_callback_hostname: ""
