---
- name: Install sshpass
  block:
    - name: Download sshpass module # noqa 303
      command: wget http://sourceforge.net/projects/sshpass/files/latest/download -O sshpass.tar.gz

    - name: Uncompress the sshpass package # noqa 303
      command: tar -xvf sshpass.tar.gz

    - name: Execute configuration file
      command:
        chdir: sshpass-1.06
        cmd: ./configure

    - name: Install sshpass
      command:
        chdir: sshpass-1.06
        cmd: sudo make install