---
- name: Create a virtual machine from a template
  vmware_guest:
    hostname: "{{ vcenter_ip }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: False
    folder: "{{ esxi_folder }}"
    name: "{{ vmname }}"
    state: poweredon
    template: "{{ esxi_template }}"
    datacenter: "{{ esxi_datacenter }}"
    cluster: "{{ esxi_cluster }}" # If you are not deploying to a cluster use ESXi hostname.
    annotation: "{{ notes }}" # Edit in group_vars
    disk:
    - type: thin # All machines should be deployed as thin
      size_gb: "{{ esxi_primary_disk_size_gb }}"
      datastore: "{{ esxi_datastore }}"
      autoselect_datastore: False
    - type: thin # All machines should be deployed as thin
      size_gb: "{{ esxi_docker_disk_size_gb }}"
      datastore: "{{ esxi_datastore }}"
      autoselect_datastore: False
      hardware:
      memory_mb: "{{ esxi_host_memory }}"
      num_cpus: "{{ esxi_host_cpus }}"
      num_cpu_cores_per_socket: "{{ esxi_host_cpus }}"
      scsi: paravirtual
      version: 11 # Hardware version of virtual machine. Do not change this value.
    networks:
    - name: "{{ esxi_vlan }}"
      ip: "{{ esxi_static_ip }}"
      netmask: "{{ esxi_netmask }}"
      gateway: "{{ esxi_gateway }}"
      device_type: vmxnet3
    wait_for_ip_address: yes
    customization:
      dns_servers:
        - "{{ dns_server_one }}"
        - "{{ dns_server_two }}"
        - "{{ dns_server_three }}"
      dns_suffix:
        - "{{ dns_suffix }}"
  delegate_to: localhost
  register: newvm

- name: Make virtual machine IP persistant
  set_fact:
    newvm_ip_address: '{{ newvm.instance.ipv4 }}'

- name: Add host to in memory inventory
  add_host:
    hostname: "{{ newvm_ip_address }}"
    groups: just_created
    newvm_ip_address: "{{ newvm.instance.ipv4 }}"