---
# This playbook will setup the Gateway's MySQL database replication.
# See the readme under roles/gateway_replicate_database for setup instructions.

- name: Replicate Gateway MySQL 8 Database
  hosts: gateway_mysql
  roles:
    - gateway_replicate_database