---
# This playbook will install PAPIM on Gatways.
# See the readme under roles/gateway_papim_install for setup instructions.

- hosts: gateway_papim_install
  gather_facts: no
  become: true

  tasks:
  - include_role:
      name: gateway_papim_install