---
# This playbook will update passwords, setup MySQL and configure a Gateway cluster without Gateway database replication. 
# See the readme under roles/gateway_common, roles/gateway_gateway_primary_db_node, and roles/gateway_processing_node for setup instructions.

- hosts: gateway
  vars:
    ansible_connection: local
  roles:
    - gateway_common

- hosts: gateway_primary_db
  vars:
    ansible_connection: local
  serial: 1
  roles:
    - gateway_configure_primary_node

- hosts: gateway_processing_node
  vars:
    ansible_connection: local
  roles:
    - gateway_configure_processing_node