---
# This playbook will restore Gateway configurations backed up by the gateway_basic_backup role.
# See the readme under roles/gateway_restore_basic_backup for setup instructions.

- name: Run gateway restore backup against provided list of gateways
  hosts: gateway
  gather_facts: no
  become: true
  tasks:
  - include_role:
      name: gateway_basic_restore_backup