---
# Runs mysql to get gateway and OTK database import against all the hosts 
- name: Execute mysql import in destination gateway 
  hosts: gateway_mysql_dest 
  serial: 1
  strategy: free
  pre_tasks:
    - name: Stop the Gateway application
      import_role:
        name: gateway_common
        tasks_from: stop_gateway
  roles:
    - gateway_import_database
