---

# This playbook will restart all destination Gateways at once.
# For rolling restart, you can uncomment the line: `serial: 1` to restart one Gateway at a time.
# The batch size may be increased from 1 if desired, and should be no more than the number of Gateways in the cluster.

- name: Add destination Gateways to group
  hosts: gateway 
  gather_facts: no
  tasks:
    - add_host:
        hostname: "{{ hostvars[item].dest }}"
        groups: gateway_dest
      with_items: "{{ groups['gateway'] }}"

- name: Restart all destination Gateways
  hosts: gateway_dest
  gather_facts: no
  # serial: 1
  tasks:
    - include_role:
        name: gateway_common
        tasks_from: restart_gateway_appliance 
