---
# This playbook will upgrade the schema version of the Gateway database.
# See the readme under roles/gateway_import_database for setup instructions.

- name: Upgrade database schema in destination gateway
  hosts: gateway_primary_db
  serial: 1
  tasks:
    - name: upgrade Gateway database schema
      delegate_to: localhost
      import_role:
        name: gateway_import_database
        tasks_from: upgrade_gateway_database_schema
