- name: Run add_slave_user.sh on {{ master_node }}
  no_log: true # don't log decrypted passwords in responses
  expect:
    command: >
      sshpass -p '{{ hostvars[master_node].ansible_ssh_pass }}' ssh {{ ansible_ssh_extra_args }}
      {{ hostvars[master_node].ansible_user }}@{{ master_node }} {{ command_add_slave_user }}
    responses:
      "Enter hostname or IP for the SLAVE:": "{{ slave_node }}"
      "Enter replication user:": "{{ hostvars[slave_node].database_repl_user }}"
      "Enter replication password:": "{{ hostvars[slave_node].database_repl_pass }}"
      "Enter MySQL root user:": "{{ hostvars[slave_node].database_admin_user }}"
      "Enter MySQL root password:": "{{ hostvars[slave_node].database_admin_pass }}"
      Is this the Primary \(1\) or Secondary \(2\) database node? : "{{ node_type }}"
      "Do you want to continue?" : "y"
  register: status
  changed_when:
    - status.rc == 0
    - '"Granting slave permissions" in status.stdout'
  failed_when: (status.rc != 0) or ("Granting slave permissions" not in status.stdout)
