---
# This task will configure replication for the primary gateway MySQL 8 database.
# root access to run /opt/SecureSpan/Appliance/bin/add_slave_user.sh and create_user.sh
# root access to update /etc/my.cnf

- name: Check the failover host is defined.
  fail:
    msg: "failover host is undefined under 'gateway_failover_db' group in your hosts file"
  when: (groups['gateway_failover_db'] | first)  is not defined

- name: Set failover hostname
  set_fact:
    failover_hostname: "{{ groups['gateway_failover_db'] | first }}.inventory_hostname"

- name: Set master hostname
  set_fact:
    master_hostname: "{{ groups['gateway_primary_db'] | first }}.inventory_hostname"

- name: Run add_slave_user.sh on master node
  include: add_slave_user.yml
  vars:
    - master_node: "{{ master_hostname }}"
    - slave_node: "{{ failover_hostname }}"
    - node_type: "1"
  delegate_to: localhost

- name: Run add_slave_user.sh on slave node
  include: add_slave_user.yml
  vars:
    - master_node: "{{ failover_hostname }}"
    - slave_node: "{{ master_hostname  }}"
    - node_type: "2"
  delegate_to: localhost

- name: Run create_slave.sh on master node
  include: create_slave.yml
  vars:
    - master_node: "{{ master_hostname }}"
    - slave_node: "{{ failover_hostname }}"
  delegate_to: localhost

- name: Run create_slave.sh on slave node
  include: create_slave.yml
  vars:
    - master_node: "{{ failover_hostname }}"
    - slave_node: "{{ master_hostname }}"
  delegate_to: localhost

- name: Verify replication has started on master node
  include: verify_replication.yml

- name: Verify replication has started on slave node
  include: verify_replication.yml
  delegate_to: "{{ failover_hostname }}"
